
services:
  web:
    image: nginx:latest
    container_name: symfony_web
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: symfony_php
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    working_dir: /var/www/html
    command: bash -c "apt-get update && apt-get install -y libicu-dev libonig-dev libxml2-dev unzip git && docker-php-ext-install intl mbstring xml opcache pdo pdo_mysql && composer install && php-fpm"



###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  db_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
