api_platform:
    title: API Platform NijiEvent
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        xml: ['application/xml']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        operations: ['GET', 'POST', 'PUT', 'DELETE']
        swagger:
        enabled: true
        versions: [3]
    
