<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSmn8qT3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSmn8qT3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSmn8qT3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSmn8qT3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSmn8qT3\App_KernelDevDebugContainer([
    'container.build_hash' => 'Smn8qT3',
    'container.build_id' => '03527e72',
    'container.build_time' => 1717578747,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSmn8qT3');
