<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.05dacd30.js',
                '/build/app.53d71f57.js',
            ],
            'css' => [
                '/build/app.b75294ae.css',
            ],
        ],
    ],
],

]];
